/**
 * 学校外链（官网等），按 id 索引；未收录的学校将提供搜索链接
 */
const SCHOOL_LINKS = {
  h1: { website: 'https://www.szhsz.cn/' },
  h2: { website: 'http://xh.sipedu.cn/' },
  h4: { website: 'https://yq.szhsz.cn/' },
  h5: { website: 'https://www.szszsy.cn/' },
  h6: { website: 'http://xh.sipedu.cn/' },
  h7: { website: 'https://www.sztu.sjtu.edu.cn/' },
  h10: { website: 'https://www.sdfz.sipedu.cn/' },
  h11: { website: 'https://www.szszsy.cn/' },
  h14: { website: 'https://www.szszsy.cn/' },
  h17: { website: 'https://www.szxqyz.com/' },
  h23: { website: 'https://www.szszsy.cn/' },
  h39: { website: 'https://www.sfls.cn/' },
  h54: { website: 'https://www.ssfls.cn/' },
  m1: { website: 'https://www.szhsz.cn/' },
  m2: { website: 'https://yq.szhsz.cn/' },
  m3: { website: 'http://xh.sipedu.cn/' },
  m4: { website: 'https://www.szszsy.cn/' },
  m5: { website: 'https://www.sztu.sjtu.edu.cn/' },
  m6: { website: 'https://www.szhsz.cn/' },
  m7: { website: 'https://www.xw.sipedu.cn/' },
  m8: { website: 'https://www.jjhxx.sipedu.cn/' },
  m9: { website: 'https://www.zhsz.suzhou.edu.cn/' },
  m10: { website: 'https://www.cqzx.suzhou.edu.cn/' },
  m12: { website: 'https://www.sfls.cn/' },
  m17: { website: 'https://www.ssfls.cn/' },
  m29: { website: 'https://www.ssfls.cn/' },
  m30: { website: 'https://www.ssfls.cn/' },
  p1: { website: 'http://xh.sipedu.cn/' },
  p2: { website: 'https://www.xw.sipedu.cn/' },
  p3: { website: 'https://www.jc.sipedu.cn/' },
  p4: { website: 'https://www.jjhxx.sipedu.cn/' },
  p5: { website: 'https://www.szsx.suzhou.edu.cn/' },
  p8: { website: 'https://www.ssfls.cn/' },
  p10: { website: 'https://www.sfls.cn/' },
  k4: { website: 'https://www.sipedu.cn/' }
};
